[project]
name = "ant-api-fundamentals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # Core
    "python-dotenv==1.0.0",
    # IA
    "anthropic"
]
